# 1 创建坐标张量

In [2]:
import torch

height = 2
width = 2

coords_h = torch.arange(height)
coords_w = torch.arange(width)
coords = torch.stack(torch.meshgrid([coords_h, coords_w]))
coords

tensor([[[0, 0],
         [1, 1]],

        [[0, 1],
         [0, 1]]])

# 2 展平

In [3]:
coords_flatten = torch.flatten(coords, 1)
coords_flatten

tensor([[0, 0, 1, 1],
        [0, 1, 0, 1]])

上述结果，生成了形状为 2x4 的张量，
- 第一行表示高度坐标
- 第二行表示宽度坐标

# 3 增加维度
- 对于高度方向，在最后增加一个新维度，使形状从 `[2, 4]` -> `[2, 4, 1]`
- 对于宽度方向，在中间增加一个新维度，使形状从 `[2, 4]` -> `[2, 1, 4]`

In [6]:
coords_flatten_1 = coords_flatten[:,:, None]
coords_flatten_2 = coords_flatten[:, None,:]

In [8]:
coords_flatten_1

tensor([[[0],
         [0],
         [1],
         [1]],

        [[0],
         [1],
         [0],
         [1]]])

In [9]:
coords_flatten_2

tensor([[[0, 0, 1, 1]],

        [[0, 1, 0, 1]]])

# 4 计算相对坐标差
对坐标进行广播
- 对coords_flatten_1 张量的形状进行扩展，从 `[2, 4, 1]` -> `[2, 4, 4]`
- 对coords_flatten_2 张量的形状进行扩展，从 `[2, 1, 4]` -> `[2, 4, 4]`

In [13]:
coords_flatten_1_broadcast = coords_flatten_1.expand(-1, -1, 4)
coords_flatten_2_broadcast = coords_flatten_2.expand(-1, 4, -1)

In [14]:
coords_flatten_1_broadcast

tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[0, 0, 0, 0],
         [1, 1, 1, 1],
         [0, 0, 0, 0],
         [1, 1, 1, 1]]])

In [16]:
coords_flatten_2_broadcast

tensor([[[0, 0, 1, 1],
         [0, 0, 1, 1],
         [0, 0, 1, 1],
         [0, 0, 1, 1]],

        [[0, 1, 0, 1],
         [0, 1, 0, 1],
         [0, 1, 0, 1],
         [0, 1, 0, 1]]])